on: push

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make node_modules
      - run: make lint
      - run: make typecheck
      - run: make test
  up-to-date:
    name: Up-to-date scripts/docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make node_modules
      - run: make build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - run: make docgen
      - name: Check uncommitted changes
        run: git add --intent-to-add . && git diff --exit-code --stat
