on: push

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: make node_modules
      - run: make lint
      - run: make format.check
      - run: make typecheck
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: make node_modules
      - run: make test
  docs:
    name: Up-to-date docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: make node_modules
      - run: make docgen
      - name: Check uncommitted changes
        run: test -z "$(git status --porcelain)"
  scripts:
    name: Up-to-date scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: make node_modules
      - run: NODE_OPTIONS='--max_old_space_size=4096' make build
      - name: Check uncommitted changes
        run: test -z "$(git status --porcelain)"
