on: push

name: CI

env:
  MAKE_YARN_FROZEN_LOCKFILE: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: make node_modules
      - name: ESLint
        run: make lint
      - name: Prettier
        run: make format.check
      - name: Typecheck
        run: make typecheck
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: make node_modules
      - name: Test
        run: make test
  docs:
    name: Up-to-date docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: make node_modules
      - name: Docgen
        run: make docgen
      - name: Check uncommitted changes
        run: test -z "$(git status --porcelain)"
  scripts:
    name: Up-to-date scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: make node_modules
      - name: Build
        run: NODE_OPTIONS='--max_old_space_size=4096' make build
      - name: Check uncommitted changes
        run: test -z "$(git status --porcelain)"
